plugins { id 'com.android.application' }

android {
    namespace 'it.simone.financeapp'
    compileSdk 35

    defaultConfig {
        applicationId 'it.simone.financeapp'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '2.4'
    }

    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
}
